# Generated by Django 3.1.4 on 2021-02-11 12:06

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='news/', verbose_name='Изображение новости')),
                ('img_alt', models.CharField(max_length=32, verbose_name='alt изображение')),
                ('date', models.DateField(verbose_name='Дата')),
                ('title', models.CharField(max_length=128, verbose_name='Загаловок')),
                ('description', models.CharField(max_length=256, verbose_name='Описание')),
                ('keywords_seo', models.CharField(max_length=1024, verbose_name='Ключевые слова для СЕО')),
                ('description_seo', models.CharField(max_length=2048, verbose_name='Описание для СЕО')),
                ('text', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.CreateModel(
            name='Feeds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_detail', models.ImageField(upload_to='feeds/', verbose_name='Изображение на странице отзывов')),
                ('img_detail_alt', models.CharField(max_length=128, verbose_name='Изображение на странице отзывов (Alt)')),
                ('img_main', models.ImageField(upload_to='feeds/', verbose_name='Изображение на главной странице')),
                ('img_main_alt', models.CharField(max_length=128, verbose_name='Изображение на главной странице (Alt)')),
                ('title', models.CharField(max_length=128, verbose_name='Заголовок')),
                ('description_short', models.TextField(verbose_name='Описание короткое')),
                ('description_long', models.TextField(verbose_name='Описание полное')),
                ('video_review', models.URLField(verbose_name='Видео')),
                ('meta_title', models.CharField(max_length=128, verbose_name='meta_ title')),
                ('meta_description', models.CharField(max_length=128, verbose_name='meta_ description')),
                ('meta_keywords', models.CharField(max_length=128, verbose_name='meta_ keywords')),
            ],
            options={
                'verbose_name': 'Отзывы',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Почта')),
                ('form', models.CharField(max_length=128, verbose_name='Форма')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='ProgramOffers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(max_length=128, verbose_name='Программа')),
                ('name', models.CharField(max_length=128, verbose_name='Имя')),
                ('phone', models.BigIntegerField(verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Заявка на программу',
                'verbose_name_plural': 'Заявки на программы',
            },
        ),
        migrations.CreateModel(
            name='SEO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(choices=[('/', 'Главная'), ('/coaching', 'О коучинге'), ('/programs', 'Программы'), ('/programs/enter-coaching', 'ВВЕДЕНИЕ В КОУЧИНГ'), ('/programs/science-and-art', 'НАУКА И ИСКУССТВО КОУЧИНГА'), ('/programs/team-coaching', 'Командный коучинг'), ('/programs/upraclencheskiy', 'Управленческий коучинг'), ('/timetable', 'Распиание'), ('/timetable-filter', 'Распиание'), ('/games', 'Трансформационные игры'), ('/about', 'О нас'), ('/article', 'Статьи'), ('/feed-list', 'Отзывы'), ('/coaches', 'Тренеры'), ('/contacts', 'Контакты')], max_length=32, unique=True, verbose_name='Адрес страницы')),
                ('title', models.CharField(max_length=128, verbose_name='Титульник страницы')),
                ('keywords', models.CharField(max_length=1024, verbose_name='Ключевые слова')),
                ('description', models.CharField(max_length=2048, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'СЕО страницы',
                'verbose_name_plural': 'СЕО страниц',
            },
        ),
        migrations.CreateModel(
            name='Trainers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='ФИО')),
                ('description', models.TextField(verbose_name='Описание')),
                ('img', models.ImageField(upload_to='coach_detail/', verbose_name='Фото')),
                ('img_alt', models.CharField(max_length=128, verbose_name='Фото альт')),
                ('meta_title', models.CharField(max_length=128, verbose_name='meta_ title')),
                ('meta_description', models.CharField(max_length=128, verbose_name='meta_ description')),
                ('meta_keywords', models.CharField(max_length=128, verbose_name='meta_ keywords')),
            ],
            options={
                'verbose_name': 'Тренер',
                'verbose_name_plural': 'Тренеры',
            },
        ),
        migrations.CreateModel(
            name='WayCouch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('way_t', models.CharField(max_length=128, verbose_name='Наименование направления')),
            ],
            options={
                'verbose_name': 'Направление коуча',
                'verbose_name_plural': 'Направления коучинга',
            },
        ),
        migrations.CreateModel(
            name='WayWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('way', models.CharField(max_length=64, verbose_name='Напрвление работы')),
                ('coach', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.trainers', verbose_name='Тренер')),
            ],
            options={
                'verbose_name': 'Направление работы',
                'verbose_name_plural': 'Направления работы',
            },
        ),
        migrations.CreateModel(
            name='Timetables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_day', models.IntegerField(verbose_name='День')),
                ('date_month', models.CharField(max_length=64, verbose_name='Месяц(словестно)')),
                ('date_full', models.DateField(verbose_name='Дата')),
                ('time_start', models.TimeField(blank=True, verbose_name='Начало в:')),
                ('time_end', models.TimeField(blank=True, verbose_name='Конец:')),
                ('long', models.CharField(blank=True, max_length=64, verbose_name='Продолжительность')),
                ('title', models.CharField(max_length=128, verbose_name='Заголовок')),
                ('description_short', models.TextField(blank=True, verbose_name='Описание короткое')),
                ('price', models.CharField(blank=True, max_length=16, verbose_name='Цена')),
                ('way', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.waycouch', verbose_name='Направление')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписания',
            },
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Заголовок')),
                ('title_short', models.CharField(max_length=64, null=True, verbose_name='Заголовок короткий')),
                ('img', models.ImageField(upload_to='games/', verbose_name='Изображение')),
                ('img_alt', models.ImageField(max_length=128, upload_to='', verbose_name='Изображение альт')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('description_short', models.TextField(verbose_name='Описание короткое')),
                ('date_day', models.IntegerField(null=True, verbose_name='День')),
                ('date_month', models.IntegerField(null=True, verbose_name='Месяц')),
                ('date_year', models.IntegerField(null=True, verbose_name='Год')),
                ('long', models.CharField(max_length=64, null=True, verbose_name='Продолжительность')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Описание')),
                ('couch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.trainers', verbose_name='Тренер')),
            ],
            options={
                'verbose_name': 'Трансформационная игра',
                'verbose_name_plural': 'Трансформационные игры',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_exp', models.IntegerField(verbose_name='Начал')),
                ('title_exp', models.CharField(max_length=256, verbose_name='Наименование учреждения')),
                ('coach', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.trainers', verbose_name='Тренер')),
            ],
            options={
                'verbose_name': 'Опыт',
                'verbose_name_plural': 'Опыта',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_ed', models.IntegerField(verbose_name='Начал')),
                ('end_ed', models.IntegerField(verbose_name='Окончил')),
                ('ed_title', models.CharField(max_length=256, verbose_name='Наименование учреждения')),
                ('coach', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.trainers', verbose_name='Тренер')),
            ],
            options={
                'verbose_name': 'Образование',
                'verbose_name_plural': 'Образования',
            },
        ),
    ]
