# Generated by Django 3.1.4 on 2021-02-11 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetables',
            name='description_short',
            field=models.TextField(blank=True, null=True, verbose_name='Описание короткое'),
        ),
        migrations.AlterField(
            model_name='timetables',
            name='long',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Продолжительность'),
        ),
        migrations.AlterField(
            model_name='timetables',
            name='price',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='timetables',
            name='time_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Конец:'),
        ),
        migrations.AlterField(
            model_name='timetables',
            name='time_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Начало в:'),
        ),
        migrations.AlterField(
            model_name='timetables',
            name='way',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.waycouch', verbose_name='Направление'),
        ),
    ]
