# Generated by Django 3.1.4 on 2020-12-09 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waycouch',
            old_name='way-t',
            new_name='way_t',
        ),
    ]
