# Generated by Django 3.1.4 on 2020-12-15 14:23

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201215_1201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name': 'Образование', 'verbose_name_plural': 'Образования'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'verbose_name': 'Опыт', 'verbose_name_plural': 'Опыта'},
        ),
        migrations.AlterModelOptions(
            name='games',
            options={'verbose_name': 'Трансформационная игра', 'verbose_name_plural': 'Трансформационные игры'},
        ),
        migrations.AlterModelOptions(
            name='timetables',
            options={'verbose_name': 'Расписание', 'verbose_name_plural': 'Расписания'},
        ),
        migrations.AlterModelOptions(
            name='trainers',
            options={'verbose_name': 'Тренер', 'verbose_name_plural': 'Тренеры'},
        ),
        migrations.AlterModelOptions(
            name='waywork',
            options={'verbose_name': 'Направление работы', 'verbose_name_plural': 'Направления работы'},
        ),
        migrations.AddField(
            model_name='games',
            name='img_alt',
            field=models.ImageField(default=1, max_length=128, upload_to='', verbose_name='Изображение альт'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainers',
            name='img_alt',
            field=models.CharField(default=1, max_length=128, verbose_name='Фото альт'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='education',
            name='coach',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.trainers', verbose_name='Тренер'),
        ),
        migrations.AlterField(
            model_name='education',
            name='ed_title',
            field=models.CharField(max_length=256, verbose_name='Наименование учреждения'),
        ),
        migrations.AlterField(
            model_name='education',
            name='end_ed',
            field=models.IntegerField(verbose_name='Окончил'),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_ed',
            field=models.IntegerField(verbose_name='Начал'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='coach',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.trainers', verbose_name='Тренер'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_exp',
            field=models.IntegerField(verbose_name='Начал'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='title_exp',
            field=models.CharField(max_length=256, verbose_name='Наименование учреждения'),
        ),
        migrations.AlterField(
            model_name='games',
            name='couch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.trainers', verbose_name='Тренер'),
        ),
        migrations.AlterField(
            model_name='games',
            name='date_day',
            field=models.IntegerField(null=True, verbose_name='День'),
        ),
        migrations.AlterField(
            model_name='games',
            name='date_month',
            field=models.IntegerField(null=True, verbose_name='Месяц'),
        ),
        migrations.AlterField(
            model_name='games',
            name='date_year',
            field=models.IntegerField(null=True, verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='games',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='games',
            name='description_short',
            field=models.TextField(verbose_name='Описание короткое'),
        ),
        migrations.AlterField(
            model_name='games',
            name='img',
            field=models.ImageField(upload_to='games/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='games',
            name='long',
            field=models.CharField(max_length=64, null=True, verbose_name='Продолжительность'),
        ),
        migrations.AlterField(
            model_name='games',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='games',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='games',
            name='title_short',
            field=models.CharField(max_length=64, null=True, verbose_name='Заголовок короткий'),
        ),
        migrations.AlterField(
            model_name='timetables',
            name='date_day',
            field=models.IntegerField(verbose_name='День'),
        ),
        migrations.AlterField(
            model_name='timetables',
            name='date_full',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='timetables',
            name='date_month',
            field=models.CharField(max_length=64, verbose_name='Месяц(словестно)'),
        ),
        migrations.AlterField(
            model_name='timetables',
            name='description_short',
            field=models.TextField(verbose_name='Описание короткое'),
        ),
        migrations.AlterField(
            model_name='timetables',
            name='long',
            field=models.CharField(max_length=64, verbose_name='Продолжительность'),
        ),
        migrations.AlterField(
            model_name='timetables',
            name='price',
            field=models.CharField(max_length=16, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='timetables',
            name='time_end',
            field=models.TimeField(verbose_name='Конец:'),
        ),
        migrations.AlterField(
            model_name='timetables',
            name='time_start',
            field=models.TimeField(verbose_name='Начало в:'),
        ),
        migrations.AlterField(
            model_name='timetables',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='timetables',
            name='way',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.waycouch', verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='trainers',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='trainers',
            name='img',
            field=models.ImageField(upload_to='coach_detail/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='trainers',
            name='title',
            field=models.CharField(max_length=128, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='waycouch',
            name='way_t',
            field=models.CharField(max_length=128, verbose_name='Наименование направления'),
        ),
        migrations.AlterField(
            model_name='waywork',
            name='coach',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.trainers', verbose_name='Тренер'),
        ),
        migrations.AlterField(
            model_name='waywork',
            name='way',
            field=models.CharField(max_length=64, verbose_name='Напрвление работы'),
        ),
    ]
