# Generated by Django 3.1.4 on 2020-12-10 07:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201209_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetables',
            name='date_full',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
