# Generated by Django 3.1.4 on 2020-12-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_timetables_date_full'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=64, verbose_name='Название страницы')),
                ('title', models.CharField(max_length=128, verbose_name='Титульник страницы')),
                ('keywords', models.CharField(max_length=1024, verbose_name='Ключевые слова')),
                ('description', models.CharField(max_length=2048, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'СЕО страницы',
                'verbose_name_plural': 'СЕО страниц',
            },
        ),
    ]
