# Generated by Django 3.1.4 on 2020-12-22 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201216_1142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offers',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='programoffers',
            options={'verbose_name': 'Заявка на программу', 'verbose_name_plural': 'Заявки на программы'},
        ),
        migrations.AddField(
            model_name='feeds',
            name='meta_description',
            field=models.CharField(default=1, max_length=128, verbose_name='meta_ description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feeds',
            name='meta_keywords',
            field=models.CharField(default=1, max_length=128, verbose_name='meta_ keywords'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainers',
            name='meta_description',
            field=models.CharField(default=1, max_length=128, verbose_name='meta_ description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainers',
            name='meta_keywords',
            field=models.CharField(default=1, max_length=128, verbose_name='meta_ keywords'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainers',
            name='meta_title',
            field=models.CharField(default=1, max_length=128, verbose_name='meta_ title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feeds',
            name='meta_title',
            field=models.CharField(max_length=128, verbose_name='meta_ title'),
        ),
        migrations.AlterField(
            model_name='offers',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='offers',
            name='form',
            field=models.CharField(max_length=128, verbose_name='Форма'),
        ),
        migrations.AlterField(
            model_name='offers',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='programoffers',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='programoffers',
            name='phone',
            field=models.BigIntegerField(verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='programoffers',
            name='program',
            field=models.CharField(max_length=128, verbose_name='Программа'),
        ),
    ]
