# Generated by Django 3.1.4 on 2020-12-10 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_seo'),
    ]

    operations = [
        migrations.AddField(
            model_name='seo',
            name='path',
            field=models.CharField(default=1, max_length=32, verbose_name='Адрес страницы'),
            preserve_default=False,
        ),
    ]
