# Generated by Django 3.1.4 on 2021-01-14 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201217_2040'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='Articles',
        ),
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
    ]
