# Generated by Django 3.1.4 on 2020-12-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_seo_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='news/', verbose_name='Изображение новости')),
                ('img_alt', models.CharField(max_length=32, verbose_name='alt изображение')),
                ('date', models.DateField(verbose_name='Дата')),
                ('title', models.CharField(max_length=128, verbose_name='Загаловок')),
                ('description', models.CharField(max_length=256, verbose_name='Описание')),
                ('keywords_seo', models.CharField(max_length=1024, verbose_name='Ключевые слова для СЕО')),
                ('description_seo', models.CharField(max_length=2048, verbose_name='Описание для СЕО')),
            ],
            options={
                'verbose_name': 'Новости',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.AlterField(
            model_name='seo',
            name='path',
            field=models.CharField(choices=[('Главная', '/'), ('О коучинге', '/coaching'), ('Программы', '/programs'), ('Распиание', '/timetable'), ('О нас', '/about'), ('Новости', '/news'), ('Отзывы', '/feed-list'), ('Тренеры', '/coaches')], max_length=32, unique=True, verbose_name='Адрес страницы'),
        ),
    ]
