# Generated by Django 3.1.4 on 2021-01-14 00:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210114_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='text',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
