# Generated by Django 3.1.4 on 2020-12-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20201210_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seo',
            name='path',
            field=models.CharField(choices=[('/', 'Главная'), ('/coaching', 'О коучинге'), ('/programs', 'Программы'), ('/timetable', 'Распиание'), ('/about', 'О нас'), ('/news', 'Новости'), ('/feed-list', 'Отзывы'), ('/coaches', 'Тренеры'), ('/contacts', 'Конатакты')], max_length=32, unique=True, verbose_name='Адрес страницы'),
        ),
    ]
